CREATE TABLE WS_MA_PHONE(
       PH_ID        NUMBER,
       PH_PR_ID     NUMBER,
       PH_TYPE      VARCHAR2(100),
       PH_AREA_CODE VARCHAR2(100),
       PH_NUMBER    VARCHAR2(100),
       CONSTRAINT WS_PH_ID_PK1 PRIMARY KEY(PH_ID)
)
/
CREATE SEQUENCE WS_SQ_PH_ID
   INCREMENT BY 1
     START WITH 1 
     NOCACHE 
     NOCYCLE
/
CREATE TABLE WS_MA_PERSON(
       PR_ID         NUMBER,
       PR_NAME       NUMBER,
       PR_BIRTH_DATE DATE,
       CONSTRAINT WS_PR_ID_PK1 PRIMARY KEY(PR_ID)
)
/
CREATE TABLE WS_MA_VEHICLE(
       VE_PR_ID NUMBER,
       VE_TYPE  VARCHAR2(25),
       PR_MODEL VARCHAR2(25),
       CONSTRAINT WS_VE_PRID_FK1 FOREIGN KEY(VE_PR_ID) REFERENCES WS_MA_PERSON(PR_ID)
)
/
CREATE SEQUENCE WS_SQ_PR_ID
   INCREMENT BY 1
     START WITH 1 
     NOCACHE 
     NOCYCLE
/
CREATE SEQUENCE WS_SQ_VE_ID
   INCREMENT BY 1
     START WITH 1 
     NOCACHE 
     NOCYCLE
/
CREATE TABLE WS_MA_CUSTOMER(
       CU_ID         NUMBER,
       CU_NAME       VARCHAR2(100),
       CU_STREET     VARCHAR2(100),
       CU_CITY       VARCHAR2(100),
       CU_CONTACT_NO VARCHAR2(20),
       CU_MAIL       VARCHAR2(50),
       CONSTRAINT WS_CU_ID_PK1 PRIMARY KEY(CU_ID)
)
/
CREATE SEQUENCE WS_SQ_CU_ID
   INCREMENT BY 1
     START WITH 1 
     NOCACHE 
     NOCYCLE
/
CREATE TABLE WS_MA_COMPANY(
       CO_ID         NUMBER,
       CO_NAME       VARCHAR2(100),
       CO_STREET     VARCHAR2(100),
       CO_CITY       VARCHAR2(100),
       CO_PRODUCT       VARCHAR2(50),
       CONSTRAINT WS_CO_ID_PK1 PRIMARY KEY(CO_ID)
)
/
CREATE SEQUENCE WS_SQ_CU_ID
   INCREMENT BY 1
     START WITH 1 
     NOCACHE 
     NOCYCLE
/


INSERT INTO WS_MA_PHONE 


select * from sam_ma_phone_elemcoll
